# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


list = [1, 2] 
while (max(list) < 4000000): 
	list.append(list[-1] + list[-2])

sum = 0 
for x in list: 
	if x % 2 == 0: sum += x 
print (sum) 